// Base de datos de habilidades blandas sugeridas
const suggestedSkills = [
    "Comunicación Efectiva",
    "Trabajo en Equipo",
    "Liderazgo",
    "Resolución de Problemas",
    "Pensamiento Crítico",
    "Adaptabilidad",
    "Gestión del Tiempo",
    "Organización",
    "Creatividad",
    "Iniciativa",
    "Responsabilidad",
    "Empatía",
    "Negociación",
    "Toma de Decisiones",
    "Paciencia",
    "Persistencia",
    "Autoconfianza",
    "Motivación",
    "Integridad",
    "Honestidad",
    "Flexibilidad",
    "Proactividad",
    "Atención al Detalle",
    "Capacidad de Aprendizaje",
    "Gestión del Estrés",
    "Colaboración",
    "Escucha Activa",
    "Persuasión",
    "Resiliencia",
    "Innovación"
];